// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "pockels.pb.h"
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace fetch {
namespace cfg {
namespace device {

namespace {

const ::google::protobuf::Descriptor* Pockels_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Pockels_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_pockels_2eproto() {
  protobuf_AddDesc_pockels_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "pockels.proto");
  GOOGLE_CHECK(file != NULL);
  Pockels_descriptor_ = file->message_type(0);
  static const int Pockels_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pockels, v_lim_max_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pockels, v_lim_min_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pockels, v_open_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pockels, v_closed_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pockels, ao_channel_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pockels, ai_channel_),
  };
  Pockels_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Pockels_descriptor_,
      Pockels::default_instance_,
      Pockels_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pockels, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pockels, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Pockels));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_pockels_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Pockels_descriptor_, &Pockels::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_pockels_2eproto() {
  delete Pockels::default_instance_;
  delete Pockels_reflection_;
}

void protobuf_AddDesc_pockels_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\rpockels.proto\022\020fetch.cfg.device\"\234\001\n\007Po"
    "ckels\022\024\n\tv_lim_max\030\001 \001(\001:\0012\022\024\n\tv_lim_min"
    "\030\002 \001(\001:\0010\022\021\n\006v_open\030\003 \001(\001:\0010\022\023\n\010v_closed"
    "\030\004 \001(\001:\0010\022\035\n\nao_channel\030\005 \001(\t:\t/Dev1/ao2"
    "\022\036\n\nai_channel\030\006 \001(\t:\n/Dev1/ai16", 192);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "pockels.proto", &protobuf_RegisterTypes);
  Pockels::default_instance_ = new Pockels();
  Pockels::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_pockels_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_pockels_2eproto {
  StaticDescriptorInitializer_pockels_2eproto() {
    protobuf_AddDesc_pockels_2eproto();
  }
} static_descriptor_initializer_pockels_2eproto_;


// ===================================================================

const ::std::string Pockels::_default_ao_channel_("/Dev1/ao2");
const ::std::string Pockels::_default_ai_channel_("/Dev1/ai16");
#ifndef _MSC_VER
const int Pockels::kVLimMaxFieldNumber;
const int Pockels::kVLimMinFieldNumber;
const int Pockels::kVOpenFieldNumber;
const int Pockels::kVClosedFieldNumber;
const int Pockels::kAoChannelFieldNumber;
const int Pockels::kAiChannelFieldNumber;
#endif  // !_MSC_VER

Pockels::Pockels()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Pockels::InitAsDefaultInstance() {
}

Pockels::Pockels(const Pockels& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Pockels::SharedCtor() {
  _cached_size_ = 0;
  v_lim_max_ = 2;
  v_lim_min_ = 0;
  v_open_ = 0;
  v_closed_ = 0;
  ao_channel_ = const_cast< ::std::string*>(&_default_ao_channel_);
  ai_channel_ = const_cast< ::std::string*>(&_default_ai_channel_);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Pockels::~Pockels() {
  SharedDtor();
}

void Pockels::SharedDtor() {
  if (ao_channel_ != &_default_ao_channel_) {
    delete ao_channel_;
  }
  if (ai_channel_ != &_default_ai_channel_) {
    delete ai_channel_;
  }
  if (this != default_instance_) {
  }
}

void Pockels::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Pockels::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Pockels_descriptor_;
}

const Pockels& Pockels::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_pockels_2eproto();  return *default_instance_;
}

Pockels* Pockels::default_instance_ = NULL;

Pockels* Pockels::New() const {
  return new Pockels;
}

void Pockels::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    v_lim_max_ = 2;
    v_lim_min_ = 0;
    v_open_ = 0;
    v_closed_ = 0;
    if (_has_bit(4)) {
      if (ao_channel_ != &_default_ao_channel_) {
        ao_channel_->assign(_default_ao_channel_);
      }
    }
    if (_has_bit(5)) {
      if (ai_channel_ != &_default_ai_channel_) {
        ai_channel_->assign(_default_ai_channel_);
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Pockels::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double v_lim_max = 1 [default = 2];
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &v_lim_max_)));
          _set_bit(0);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(17)) goto parse_v_lim_min;
        break;
      }
      
      // optional double v_lim_min = 2 [default = 0];
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_v_lim_min:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &v_lim_min_)));
          _set_bit(1);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(25)) goto parse_v_open;
        break;
      }
      
      // optional double v_open = 3 [default = 0];
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_v_open:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &v_open_)));
          _set_bit(2);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(33)) goto parse_v_closed;
        break;
      }
      
      // optional double v_closed = 4 [default = 0];
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_v_closed:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &v_closed_)));
          _set_bit(3);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_ao_channel;
        break;
      }
      
      // optional string ao_channel = 5 [default = "/Dev1/ao2"];
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_ao_channel:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_ao_channel()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->ao_channel().data(), this->ao_channel().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_ai_channel;
        break;
      }
      
      // optional string ai_channel = 6 [default = "/Dev1/ai16"];
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_ai_channel:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_ai_channel()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->ai_channel().data(), this->ai_channel().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Pockels::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional double v_lim_max = 1 [default = 2];
  if (_has_bit(0)) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->v_lim_max(), output);
  }
  
  // optional double v_lim_min = 2 [default = 0];
  if (_has_bit(1)) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->v_lim_min(), output);
  }
  
  // optional double v_open = 3 [default = 0];
  if (_has_bit(2)) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->v_open(), output);
  }
  
  // optional double v_closed = 4 [default = 0];
  if (_has_bit(3)) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->v_closed(), output);
  }
  
  // optional string ao_channel = 5 [default = "/Dev1/ao2"];
  if (_has_bit(4)) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->ao_channel().data(), this->ao_channel().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      5, this->ao_channel(), output);
  }
  
  // optional string ai_channel = 6 [default = "/Dev1/ai16"];
  if (_has_bit(5)) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->ai_channel().data(), this->ai_channel().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      6, this->ai_channel(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Pockels::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional double v_lim_max = 1 [default = 2];
  if (_has_bit(0)) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->v_lim_max(), target);
  }
  
  // optional double v_lim_min = 2 [default = 0];
  if (_has_bit(1)) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->v_lim_min(), target);
  }
  
  // optional double v_open = 3 [default = 0];
  if (_has_bit(2)) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->v_open(), target);
  }
  
  // optional double v_closed = 4 [default = 0];
  if (_has_bit(3)) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->v_closed(), target);
  }
  
  // optional string ao_channel = 5 [default = "/Dev1/ao2"];
  if (_has_bit(4)) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->ao_channel().data(), this->ao_channel().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->ao_channel(), target);
  }
  
  // optional string ai_channel = 6 [default = "/Dev1/ai16"];
  if (_has_bit(5)) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->ai_channel().data(), this->ai_channel().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->ai_channel(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Pockels::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional double v_lim_max = 1 [default = 2];
    if (has_v_lim_max()) {
      total_size += 1 + 8;
    }
    
    // optional double v_lim_min = 2 [default = 0];
    if (has_v_lim_min()) {
      total_size += 1 + 8;
    }
    
    // optional double v_open = 3 [default = 0];
    if (has_v_open()) {
      total_size += 1 + 8;
    }
    
    // optional double v_closed = 4 [default = 0];
    if (has_v_closed()) {
      total_size += 1 + 8;
    }
    
    // optional string ao_channel = 5 [default = "/Dev1/ao2"];
    if (has_ao_channel()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->ao_channel());
    }
    
    // optional string ai_channel = 6 [default = "/Dev1/ai16"];
    if (has_ai_channel()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->ai_channel());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Pockels::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Pockels* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Pockels*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Pockels::MergeFrom(const Pockels& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from._has_bit(0)) {
      set_v_lim_max(from.v_lim_max());
    }
    if (from._has_bit(1)) {
      set_v_lim_min(from.v_lim_min());
    }
    if (from._has_bit(2)) {
      set_v_open(from.v_open());
    }
    if (from._has_bit(3)) {
      set_v_closed(from.v_closed());
    }
    if (from._has_bit(4)) {
      set_ao_channel(from.ao_channel());
    }
    if (from._has_bit(5)) {
      set_ai_channel(from.ai_channel());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Pockels::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Pockels::CopyFrom(const Pockels& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Pockels::IsInitialized() const {
  
  return true;
}

void Pockels::Swap(Pockels* other) {
  if (other != this) {
    std::swap(v_lim_max_, other->v_lim_max_);
    std::swap(v_lim_min_, other->v_lim_min_);
    std::swap(v_open_, other->v_open_);
    std::swap(v_closed_, other->v_closed_);
    std::swap(ao_channel_, other->ao_channel_);
    std::swap(ai_channel_, other->ai_channel_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Pockels::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Pockels_descriptor_;
  metadata.reflection = Pockels_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace device
}  // namespace cfg
}  // namespace fetch

// @@protoc_insertion_point(global_scope)
