// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shutter.proto

#ifndef PROTOBUF_shutter_2eproto__INCLUDED
#define PROTOBUF_shutter_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace fetch {
namespace cfg {
namespace device {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_shutter_2eproto();
void protobuf_AssignDesc_shutter_2eproto();
void protobuf_ShutdownFile_shutter_2eproto();

class Shutter;

// ===================================================================

class Shutter : public ::google::protobuf::Message {
 public:
  Shutter();
  virtual ~Shutter();
  
  Shutter(const Shutter& from);
  
  inline Shutter& operator=(const Shutter& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Shutter& default_instance();
  
  void Swap(Shutter* other);
  
  // implements Message ----------------------------------------------
  
  Shutter* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Shutter& from);
  void MergeFrom(const Shutter& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional uint32 open = 1 [default = 1];
  inline bool has_open() const;
  inline void clear_open();
  static const int kOpenFieldNumber = 1;
  inline ::google::protobuf::uint32 open() const;
  inline void set_open(::google::protobuf::uint32 value);
  
  // optional uint32 closed = 2 [default = 0];
  inline bool has_closed() const;
  inline void clear_closed();
  static const int kClosedFieldNumber = 2;
  inline ::google::protobuf::uint32 closed() const;
  inline void set_closed(::google::protobuf::uint32 value);
  
  // optional string do_channel = 3 [default = "/Dev1/port0/line0"];
  inline bool has_do_channel() const;
  inline void clear_do_channel();
  static const int kDoChannelFieldNumber = 3;
  inline const ::std::string& do_channel() const;
  inline void set_do_channel(const ::std::string& value);
  inline void set_do_channel(const char* value);
  inline void set_do_channel(const char* value, size_t size);
  inline ::std::string* mutable_do_channel();
  
  // @@protoc_insertion_point(class_scope:fetch.cfg.device.Shutter)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::uint32 open_;
  ::google::protobuf::uint32 closed_;
  ::std::string* do_channel_;
  static const ::std::string _default_do_channel_;
  friend void  protobuf_AddDesc_shutter_2eproto();
  friend void protobuf_AssignDesc_shutter_2eproto();
  friend void protobuf_ShutdownFile_shutter_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Shutter* default_instance_;
};
// ===================================================================


// ===================================================================

// Shutter

// optional uint32 open = 1 [default = 1];
inline bool Shutter::has_open() const {
  return _has_bit(0);
}
inline void Shutter::clear_open() {
  open_ = 1u;
  _clear_bit(0);
}
inline ::google::protobuf::uint32 Shutter::open() const {
  return open_;
}
inline void Shutter::set_open(::google::protobuf::uint32 value) {
  _set_bit(0);
  open_ = value;
}

// optional uint32 closed = 2 [default = 0];
inline bool Shutter::has_closed() const {
  return _has_bit(1);
}
inline void Shutter::clear_closed() {
  closed_ = 0u;
  _clear_bit(1);
}
inline ::google::protobuf::uint32 Shutter::closed() const {
  return closed_;
}
inline void Shutter::set_closed(::google::protobuf::uint32 value) {
  _set_bit(1);
  closed_ = value;
}

// optional string do_channel = 3 [default = "/Dev1/port0/line0"];
inline bool Shutter::has_do_channel() const {
  return _has_bit(2);
}
inline void Shutter::clear_do_channel() {
  if (do_channel_ != &_default_do_channel_) {
    do_channel_->assign(_default_do_channel_);
  }
  _clear_bit(2);
}
inline const ::std::string& Shutter::do_channel() const {
  return *do_channel_;
}
inline void Shutter::set_do_channel(const ::std::string& value) {
  _set_bit(2);
  if (do_channel_ == &_default_do_channel_) {
    do_channel_ = new ::std::string;
  }
  do_channel_->assign(value);
}
inline void Shutter::set_do_channel(const char* value) {
  _set_bit(2);
  if (do_channel_ == &_default_do_channel_) {
    do_channel_ = new ::std::string;
  }
  do_channel_->assign(value);
}
inline void Shutter::set_do_channel(const char* value, size_t size) {
  _set_bit(2);
  if (do_channel_ == &_default_do_channel_) {
    do_channel_ = new ::std::string;
  }
  do_channel_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Shutter::mutable_do_channel() {
  _set_bit(2);
  if (do_channel_ == &_default_do_channel_) {
    do_channel_ = new ::std::string(_default_do_channel_);
  }
  return do_channel_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace device
}  // namespace cfg
}  // namespace fetch

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_shutter_2eproto__INCLUDED
