##
# Locate NI-DAQmx
#
# REQUIRED ENVIRONMENT VARIABLES
# ------------------------------
#
# NIEXTCCOMPILERSUPP (windows)
#
# OUTPUT VARIABLES
# ----------------
# NIDAQMX_LIBRARY
# NIDAQMX_INCLUDE_DIR
# NIDAQMX_FOUND
# HAVE_NIDAQMX
#

#
FUNCTION(_NIDAQMX_ASSERT _VAR _MSG)
IF(NOT ${_VAR})
  IF(${NIDAQMX_FIND_REQUIRED})
    MESSAGE(FATAL_ERROR ${_MSG}) 
  ELSE()
    MESSAGE(STATUS ${_MSG}) 
  ENDIF()
ENDIF()
ENDFUNCTION(_NIDAQMX_ASSERT)

#
set(NIDAQMX_FOUND "NO")
set(HAVE_NIDAQMX 0)

find_path(NIDAQMX_INCLUDE_DIR NIDAQmx.h
    HINTS
    $ENV{NIEXTCCOMPILERSUPP}
    PATH_SUFFIXES include
)
_NIDAQMX_ASSERT(NIDAQMX_INCLUDE_DIR "Could not find NIDAQmx.h")

find_library(NIDAQMX_LIBRARY NIDAQmx.lib
  HINTS
  $ENV{NIEXTCCOMPILERSUPP}
  PATH_SUFFIXES lib32/msvc lib64/msvc
  )
_NIDAQMX_ASSERT(NIDAQMX_LIBRARY "Could not find NIDAQmx.lib")

set(NIDAQMX_FOUND "YES")
set(HAVE_NIDAQMX 1)
# message("NIDAQMX_INCLUDE_DIR is ${NIDAQMX_INCLUDE_DIR}")
# message("NIDAQMX_LIBRARY is ${NIDAQMX_LIBRARY}")
