##
# Locate Physik Instrument's GCS API for the C-843
#        stage controller
#
# OUTPUT VARIABLES
# ----------------
# C843_LIBRARY
# C843_INCLUDE_DIR
# C843_FOUND
#

#
FUNCTION(_C843_ASSERT _VAR _MSG)
IF(NOT ${_VAR})
  IF(${C843_FIND_REQUIRED})
    MESSAGE(FATAL_ERROR ${_MSG}) 
  ELSE()
    MESSAGE(STATUS ${_MSG}) 
  ENDIF()
ENDIF()
ENDFUNCTION(_C843_ASSERT)

#
set(C843_FOUND "NO")

find_path(C843_INCLUDE_DIR C843_GCS_DLL.H
    HINTS
    $ENV{PROGRAMFILES}/PI/C-843/C843_GCS_DLL
)
_C843_ASSERT(C843_INCLUDE_DIR "Could not find C843_GCS_DLL.h")

find_library(C843_LIBRARY C843_GCS_DLL.lib
  HINTS
  $ENV{PROGRAMFILES}/PI/C-843/C843_GCS_DLL
)
_C843_ASSERT(C843_LIBRARY "Could not find ATSApi.lib")

set(C843_FOUND "YES")
# message("C843_INCLUDE_DIR is ${C843_INCLUDE_DIR}")
# message("C843_LIBRARY is ${C843_LIBRARY}")


